config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  resources :jobs

  root 'jobs#index'

end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	def index
		@jobs = Job.all
	end

	def new
		@job = Job.new
	end

	def create
		p "Enter create job method"
		Job.create(job_params)
  		redirect_to jobs_path
		# render :index <-- redirect to index
	end

	def job_params
		params.require(:job).permit(:title, :description)
	end

	def edit
		@job = Job.find(params[:id])
	end

	def update
		@job = Job.find(params[:id])
  		@job.update_attributes(job_params)
	  	redirect_to jobs_path
	end

	def destroy
		@job = Job.find(params[:id])
		@job.destroy
		redirect_to jobs_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for @job do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description, size: '60x6' %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Edit Posting</h1>

<%= render "form" %>

app/views/jobs/index.html.erb
<h1>RailsBridgeCorp Open Jobs</h1>

<!-- etiquetas que empiezan con % no da resultado solo ejecuta la acción "mandas comandos" -->
<% @jobs.each do |job| %>
  <!-- etiquetas que empiezan con %= se toma el valor de la variable linkeada "esperas resultados" -->
  <h3><%= job.title %></h3>
  <p><%= job.description %></p>
  <h5><%= link_to "Edit Posting", edit_job_path(job)%></h5>
  <h5><%= link_to 'Delete Posting', job, method: :delete %></h5>
<% end %>

app/views/jobs/new.html.erb
<h1>Add a job</h1>

<%= form_for @job do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description, size: '60x6' %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>JobBoard</title>
	<%= stylesheet_link_tag    "application", media: "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="container">

		<div class="navbar navbar-default">
	    	<div class="navbar-header">
	      		<a class="navbar-brand" href="#">Message Board</a>
	    	</div>
	    	<ul class="nav navbar-nav">
	      		<!--<li class="active"><a href="/">Home</a></li>-->
	      		<li class="active"><%= link_to "Home", jobs_path %></li>
	    	</ul>
	    	<ul class="nav navbar-nav">
	      		<!--<li class=""><a href="/new">Add Job</a></li>-->
	      		<li><%= link_to "Add Job", new_job_path %></li>
	    	</ul>
	    	<p class="navbar-text pull-right">logged_in_user@email.com | <a href="log_out_link_here">Log Out</a></p>
	    	<!--<div class="clearfix"></div>-->
		</div>

		<p class="notice"><%= notice %></p>
 		<p class="alert"><%= alert %></p>

		<%= yield %>
	</div>	

</body>
</html>